substitutions:
  _REGION: us-central1
  _JOB_NAME: weekend-agent
  _REPO: containers

steps:
# 1) Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t','${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_JOB_NAME}:${COMMIT_SHA}',
    './job-weekend'
  ]

# 2) Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_JOB_NAME}:${COMMIT_SHA}'
  ]

# 3) Try to create the Cloud Run Job (ignore error if it exists)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - -ceu
    - |
      gcloud run jobs create ${_JOB_NAME} \
        --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_JOB_NAME}:${COMMIT_SHA} \
        --region ${_REGION} \
        --service-account trading-runtime@${PROJECT_ID}.iam.gserviceaccount.com \
        --set-env-vars PROJECT_ID=${PROJECT_ID},BQ_DATASET=trading \
        --set-secrets DISCORD_WEBHOOK=DISCORD_WEBHOOK:latest \
        --max-retries 0 --task-timeout 120s \
      || echo "Job already exists, skipping create"

# 4) Always update the Job to use the new image & env
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'run','jobs','update','${_JOB_NAME}',
      '--region','${_REGION}',
      '--image','${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_JOB_NAME}:${COMMIT_SHA}',
      '--set-env-vars','PROJECT_ID=${PROJECT_ID},BQ_DATASET=trading',
      '--set-secrets','DISCORD_WEBHOOK=DISCORD_WEBHOOK:latest',
      '--service-account','trading-runtime@${PROJECT_ID}.iam.gserviceaccount.com'
    ]

images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_JOB_NAME}:${COMMIT_SHA}'
